package ExceptionHandiling;

public class Test1 {
	public static void add() {
		System.out.println("addition");
	}

	public static void main(String[] args) {
		//try {
		int i=10;
		//}
		//catch(ArithmeticException a) { 
		System.out.println("AE is handled");
		//}
		System.out.println("hello java");
		Test1.add();
	

	}

}
